turn_on:
  name: Turn on extrapolation scene
  description: 'Imroved, more advanced version of the native "Activate scene" action (scene.turn_on). Activate one or more extrapolation scenes with optional brightness modifications and other advanced options. With a brightness modification, the scene will turn on directly to that brightness (a weakness with the default service is that you first have to activate the scene, and then dim the lights afterwards - which makes for a jarring experience).'
  fields:
    entity_id:
      name: Scenes
      description: Select one or more extrapolation scenes to activate
      required: true
      selector:
        entity:
          domain: scene
          integration: scene_extrapolation
          multiple: true
    transition:
      name: Transition time
      description: Defaults to 0 seconds
      required: false
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          unit_of_measurement: "s"
          mode: slider
    brightness_modifier:
      name: Brightness modifier
      description: Modifies the brightness percentage of each light after the extrapolation is calculated
      required: false
      default: 0
      selector:
        number:
          min: -100
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
    transition_modifier:
      name: Transition modifier (More dynamic way to change the brightness)
      description: Shift the extrapolation towards noon or dusk/dawn (whichever is closer). Positive values shift towards noon (brighter), negative values shift towards low-light scenes (dimmer)
      required: false
      default: 0
      selector:
        number:
          min: -100
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
    advanced_options:
      name: Advanced options (for testing purposes)
      collapsed: true
      fields:
        target_date_time:
          name: Change the time
          description: "Preview the scene at a different time. Eg. pretend it's summer/winter (defaults to current time)"
          required: false
          selector:
            datetime:
        location:
          name: Location
          description: "Override the location for solar event calculations (defaults to Home Assistant's configured location)"
          required: false
          selector:
            location:
